- src/App.js
r? @gmartin02 
cc @sophiahunt
Removed React code that called the `graphql` operation `echo`. This operation does not exist anymore and was only used to show an example of what API calling could look like.
Frontend is failing to build since the `echo` import is no longer existent. This will unblock the CI/CD pipeline.
Can rollback to previous commit
> Removing non-existent echo() function

- src/components/Auth.js
- src/index.js
r? @gmartin02 
cc @sophiahunt 
Connecting AWS Cognito Auth to Login/Signup page. Added some more page options, such as "confirmSignUp" and "signedIn".
**TODO:** Style and route the new page options correctly.
Lab due 3/20/2023. To further progress on web app development.
> Adding Cognito Auth to Web

- src/AppEntry.js
- src/components/HouseholdButton.js
- src/components/InitialPage.js
- src/components/auth/Auth.js
- src/components/auth/Login.js
- src/components/styles.js
> mobile initial page

- src/AppEntry.js
- src/components/auth/Auth.js
- src/components/auth/ConfirmRegister.js
- src/components/auth/Login.js
- src/components/auth/Register.js
r? @diti85 
cc @evoth 
This change introduces Cognito Auth API calls to the Login and Register page, along with adding a ConfirmRegister page.
Something to note: in order for the app to work correctly, the `src` directory must have a valid `aws-exports` file.
Adding Auth implementation to the backend, in accordance to exposition deadlines.
Manually tested on web (Chrome).
> Connecting mobile to Cognito

- amplify/.config/project-config.json
- amplify/backend/api/householdapp/schema.graphql
- amplify/backend/function/addMessageToChatRoom/addMessageToChatRoom-cloudformation-template.json
- amplify/backend/function/addMessageToChatRoom/src/yarn.lock
- amplify/backend/function/completeTask/completeTask-cloudformation-template.json
- amplify/backend/function/deleteListCustom/deleteListCustom-cloudformation-template.json
- amplify/backend/function/deleteTask/deleteTask-cloudformation-template.json
- src/graphql/mutations.js
- src/graphql/queries.js
- src/graphql/subscriptions.js
- src/models/index.d.ts
- src/models/schema.js
r? @christiandur4nt 
cc @wge123 
Made a quick edit to the `mutation` objects inside of `@model` tags in the GraphQL Schema.
Some objects were missing names for the auto-created CRUD operations we wanted, making them not appear.
Quick fix, allowing critical operations to be visible.
Manually tested in AWS.
> [API] added proper mutation object in @model tags

- .gitignore
- .graphqlconfig.yml
- amplify/backend/api/householdapp/schema.graphql
- amplify/backend/function/addMessageToChatRoom/src/yarn.lock
- amplify/backend/function/deleteEvent/deleteEvent-cloudformation-template.json
- amplify/backend/function/graphQlLambdaAuthorizerc6ebb49e/src/index.js
- amplify/backend/function/largeprojectCommonLayer/largeprojectCommonLayer-awscloudformation-template.json
- amplify/backend/function/largeprojectCommonLayer/parameters.json
- amplify/backend/function/removeUserFromHouseHold/removeUserFromHouseHold-cloudformation-template.json
- package-lock.json
- package.json
- src/App.js
- src/api/fetching.js
- src/api/mutating.js
- src/api/subscribing.js
- src/components/add/Add.js
- src/components/list/List.js
- src/components/listItem/ListItem.js
- src/containers/middle/Middle.js
- src/containers/sidebar/Sidebar.js
- src/graphql/mutations.js
- src/graphql/queries.js
- src/graphql/subscriptions.js
- src/index.js
r? @zacharyblum2 @christiandur4nt 
cc @gmartin02 @sophiahunt 
Backend:
- added two subscriptions to Schema and Authorizer
Frontend:
- implemented two subscriptions for ListItems
- extracted some API calls into an `api` folder for better organiation
- TODO: there's still some API calls I need to move over
- slight name changes
To implement extract and implement better API calls. Along with the subscriptions feature, which could help set us apart from competitors.
> Added ListItem subscriptions and an API folder

- amplify/backend/api/householdapp/schema.graphql
- amplify/backend/function/largeprojectCommonLayer/largeprojectCommonLayer-awscloudformation-template.json
- amplify/backend/function/largeprojectCommonLayer/parameters.json
- src/api/fetching.js
- src/api/hooks.js
- src/api/mutating.js
- src/api/subscribing.js
- src/components/AuthUser.js
- src/components/add/Add.js
- src/components/auth/Auth.js
- src/components/householdinfo/Householdinfo.js
- src/components/list/List.js
- src/containers/middle/Middle.js
- src/containers/sidebar/Sidebar.js
- src/graphql/mutations.js
- src/graphql/queries.js
- src/graphql/subscriptions.js
- src/index.js
- src/pages/dashboard/Dashboard.js
- src/pages/dashboard/HouseHoldContext.js
r? @zacharyblum2 @christiandur4nt 
cc @gmartin02 @sophiahunt 
- Custom hooks to make API calls + subscriptions were created.
- API calls were added:
- editHouseHold (only the name)
- editHouseHoldMember (only the nickname)
- addUser
- removeUser
- Some other API calls were centralized under the `api` folder.
Critical for MVP implementation.
> Added api folder and various change

- src/components/GlobalStyles/GlobalStyles.js
- src/components/householdinfo/householdinfo.css
- src/containers/sidebar/sidebar.css
r? 
cc 
Fixes minor visual issues
> fixed minor visual issues on the sidebar

- .graphqlconfig.yml
- package-lock.json
- src/AppEntry.js
- src/api/fetching.js
- src/api/hooks.js
- src/api/mutating.js
- src/api/subscribing.js
- src/components/App.js
- src/components/HouseHoldContext.js
- src/components/auth/ConfirmRegister.js
- src/components/auth/Login.js
- src/components/home/events/Events.js
- src/components/home/lists/List.js
- src/components/home/lists/Lists.js
- src/components/home/mockData.js
- src/components/home/tasks/Tasks.js
- src/components/households/CreateHousehold.js
- src/components/households/InitialPage.js
- src/graphql/mutations.js
- src/graphql/queries.js
- src/graphql/subscriptions.js
- src/utils/auth.js
r? @diti85 @evoth 
cc 
- Added API calls and some custom hooks to fetch data.
- Please review some of the changes and examples in the code for how to call the API. For instance, in List.js we call `updateExistingItem`.
- For another example, we use fetchHouseHolds instead of what we previously had. And we use the custom hooks `useListsData` for instance to fetch all of the List data.
Note: I tried implementing the "check off item" to call an API update, but it only calls it when it's first checked, not when it's "unchecked". I will leave that to you guys for now @diti85 @evoth.
TODO:
- Bring over more API calls.
- Help with implementation
Critical to MVP implementation.
> Introducing api folder and custom hooks

- src/api/fetching.js
- src/api/mutating.js
- src/components/addHousehold/AddHousehold.js
- src/components/form/Form.js
r? @zacharyblum2 @gmartin02
cc @wge123 
- Removed old `createList` implementation that was giving errors in favor of new one being implemented by @wge123.
- Rearranged the `AddHouseHold` code to work. Before, with the new `api` folder implementation, it was not working.
Crucial for MVP.
> fixing AddHouseHold to work with new API implementations

- src/api/mutating.js
- src/containers/middle/Middle.js
r? @carlos-jmh 
cc @wge123 
Added the required EventHandler and Event mutations to the frontend mutations.js file, so they are ready for use. 
Required for MVP.
Middle.js useEffect() hook. 
Can rollback to prev commit
> added eventhandler implementations

- src/api/mutating.js
- src/containers/middle/Middle.js
r? @carlos-jmh 
cc 
Added update task and delete task implementations to mutating.js
Need for MVP !!!
Middle.js
Can Rollback
> Added task implementations

- package-lock.json
- package.json
- src/components/App.js
- src/components/Auth.js
- src/components/HouseHoldContext.js
- src/components/SideBar.js
- src/components/UserContext.js
- src/components/auth/Login.js
- src/components/home/AddButton.js
- src/components/home/HeaderBar.js
- src/components/home/events/AddEvent.js
- src/components/home/events/Calendar.js
- src/components/home/events/EditEvent.js
- src/components/home/events/Event.js
- src/components/home/events/Events.js
- src/components/home/lists/Lists.js
- src/components/home/mockData.js
- src/components/households/InitialPage.js
- src/components/styles.js
- src/graphql/queries.js
r? 
cc 
All changes we discussed on our call on 4/28,
Edit Events changes. 
Add Event screen done (ready to be connected to backend).
Drawer npm package.
Sidebar Added. Still need to add functionality and design it more.
Backend Implementation:
Calendar connected to backend.
When you click Events tab and Lists tab it fetches the data from backend and attaches it to houseHold object.
Closer to MVP.
Manually tested on iOS device
> Mobile events backend

- package-lock.json
- package.json
- src/api/hooks.js
- src/api/mutating.js
- src/api/subscribing.js
- src/components/home/lists/EditList.js
- src/components/home/lists/List.js
- src/components/home/lists/ListItem.js
- src/components/home/lists/Lists.js
r? @diti85 @carlos-jmh 
cc 
Started connecting list to the backend, though there are some bugs due to conflicting means of state management (working on a fix for this)
Core app functionality
Tested on device
Revert to previous commit
> List backend connection (buggy)

- src/api/fetching.js
- src/api/hooks.js
- src/api/mutating.js
- src/api/subscribing.js
- src/components/home/lists/Lists.js
- src/graphql/mutations.js
- src/graphql/queries.js
- src/graphql/subscriptions.js
r? @diti85 @evoth 
cc 
- Added more API calls
- Added more subscriptions
MVP completion.
> [Mobile] all APIs in here and one more sub

- src/api/mutating.js
r? @diti85 
cc 
EventHandlers take a title now. Added it to the `mutations.js` file.
MVP completion.
> fixing dumb little thing

- src/api/mutating.js
- src/api/subscribing.js
- src/components/CustomButton.js
- src/components/SideBar.js
- src/components/home/events/AddEvent.js
- src/components/home/events/Calendar.js
- src/components/home/events/EditEvent.js
- src/components/home/events/Event.js
- src/components/home/events/Events.js
- src/components/households/CreateHousehold.js
- src/components/styles.js
r? 
cc 
Sidebar pretty much finished. Signout/Signin functionality added.  Last thing to do is to implement button to change theme (dark/light)
Edited datetimepicker with the hope of not crashing the app when running it on android.
Fixed CreateHousehold as it previously was not navigating you to Events page after creating a new household nor was it setting the householdContext to the new household.
Removed some unneccessary console.logs throughout.
MVP
Manually tested on iOS only.
Can rollback to previous commit
> Sidebar / DateTimePicker/ CreateHousehold changes

- amplify/backend/function/createEventHandler/src/index.js
r? @zacharyblum2 @christiandur4nt 
cc @wge123 
- Added createdAt, updatedAt, __typename, _lastChangedAt, and _version to Events with Once frequency.
MVP completion.
> Fix some default fields that were not set

- src/App.js
- src/api/hooks.js
- src/components/GlobalStyles/GlobalStyles.js
- src/components/ItemInfo/ItemInfo.css
- src/components/ItemInfo/ItemInfo.js
- src/components/Theme/Theme.js
- src/components/dropdown/Dropdown.js
- src/components/dropdown/dropdown.css
- src/components/task/Task.js
- src/containers/middle/Middle.js
- src/containers/sidebar/Sidebar.js
- src/index.js
> UI changed

- src/api/mutating.js
r? @carlos-jmh @diti85 
cc 
Added a "title" parameter for the editEventHandler function in mutaitng.js that was missing.
Required for MVP.
Tested via faith that it will work.
Can rollback.
> fixed editEventHandler to include title

- src/components/App.js
- src/components/SideBar.js
- src/components/Wrappy.js
- src/components/home/lists/EditList.js
- src/components/home/lists/List.js
- src/components/home/tasks/Tasks.js
- src/components/households/CreateHousehold.js
- src/components/households/InitialPage.js
r? @evoth @diti85 
cc 
- Auth fixeed (sign out, household not updating, etc...)
- Small List Item deletion fix
MVP.
Manual.
> Auth fix, and small List fix

- src/api/hooks.js
- src/components/task/Task.js
> fix build error

- src/components/add/Add.js
- src/components/dropdown/Dropdown.js
- src/components/dropdown/dropdown.css
- src/components/events/Events.js
- src/components/form/Form.js
- src/components/householdinfo/Householdinfo.js
- src/components/list/List.js
- src/components/task/Task.js
- src/components/task/task.css
- src/components/tasklist/TaskList.js
- src/containers/middle/Middle.js
> UI changes and general code cleanup
